<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>recorderctl</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Recorder.Application/Recorder.Application.csproj" />
  </ItemGroup>
</Project>
